from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float64

entity = Entity(
    name="network_flow",
    join_keys=["flow_id"],
)





source = FileSource(
    path="../../data/featured/selected_features.parquet",
    timestamp_field="event_timestamp",
)

feature_view = FeatureView(
    name="network_intrusion_features",
    entities=[entity],
    ttl=None,
    schema=[
        Field(name="Dst Port", dtype=Float64),
        Field(name="Protocol", dtype=Float64),
        Field(name="Flow Duration", dtype=Float64),
        Field(name="Tot Fwd Pkts", dtype=Float64),
        Field(name="Tot Bwd Pkts", dtype=Float64),
        Field(name="TotLen Fwd Pkts", dtype=Float64),
Field(name="TotLen Bwd Pkts", dtype=Float64),
Field(name="Fwd Pkt Len Max", dtype=Float64),
Field(name="Fwd Pkt Len Min", dtype=Float64),
Field(name="Fwd Pkt Len Mean", dtype=Float64),
Field(name="Fwd Pkt Len Std", dtype=Float64),
Field(name="Bwd Pkt Len Max", dtype=Float64),
Field(name="Bwd Pkt Len Min", dtype=Float64),
Field(name="Bwd Pkt Len Mean", dtype=Float64),
Field(name="Bwd Pkt Len Std", dtype=Float64),
Field(name="Flow Byts/s", dtype=Float64),
Field(name="Flow Pkts/s", dtype=Float64),
Field(name="Flow IAT Mean", dtype=Float64),
Field(name="Flow IAT Std", dtype=Float64),
Field(name="Flow IAT Max", dtype=Float64),
Field(name="Flow IAT Min", dtype=Float64),
Field(name="Fwd IAT Tot", dtype=Float64),
Field(name="Fwd IAT Mean", dtype=Float64),
Field(name="Fwd IAT Std", dtype=Float64),
Field(name="Fwd IAT Max", dtype=Float64),
Field(name="Fwd IAT Min", dtype=Float64),
Field(name="Bwd IAT Tot", dtype=Float64),
Field(name="Bwd IAT Mean", dtype=Float64),
Field(name="Bwd IAT Std", dtype=Float64),
Field(name="Bwd IAT Max", dtype=Float64),
Field(name="Bwd IAT Min", dtype=Float64),
Field(name="Fwd PSH Flags", dtype=Float64),
Field(name="Bwd PSH Flags", dtype=Float64),
Field(name="Fwd URG Flags", dtype=Float64),
Field(name="Bwd URG Flags", dtype=Float64),
Field(name="Fwd Header Len", dtype=Float64),
Field(name="Bwd Header Len", dtype=Float64),
Field(name="Fwd Pkts/s", dtype=Float64),
Field(name="Bwd Pkts/s", dtype=Float64),
Field(name="Pkt Len Min", dtype=Float64),
Field(name="Pkt Len Max", dtype=Float64),
Field(name="Pkt Len Mean", dtype=Float64),
Field(name="Pkt Len Std", dtype=Float64),
Field(name="Pkt Len Var", dtype=Float64),
Field(name="FIN Flag Cnt", dtype=Float64),
Field(name="SYN Flag Cnt", dtype=Float64),
Field(name="RST Flag Cnt", dtype=Float64),
Field(name="PSH Flag Cnt", dtype=Float64),
Field(name="ACK Flag Cnt", dtype=Float64),
Field(name="URG Flag Cnt", dtype=Float64),
Field(name="CWE Flag Count", dtype=Float64),
Field(name="ECE Flag Cnt", dtype=Float64),
Field(name="Down/Up Ratio", dtype=Float64),
Field(name="Pkt Size Avg", dtype=Float64),
Field(name="Fwd Seg Size Avg", dtype=Float64),
Field(name="Bwd Seg Size Avg", dtype=Float64),
Field(name="Fwd Byts/b Avg", dtype=Float64),
Field(name="Fwd Pkts/b Avg", dtype=Float64),
Field(name="Fwd Blk Rate Avg", dtype=Float64),
Field(name="Bwd Byts/b Avg", dtype=Float64),
Field(name="Bwd Pkts/b Avg", dtype=Float64),
Field(name="Bwd Blk Rate Avg", dtype=Float64),
Field(name="Subflow Fwd Pkts", dtype=Float64),
Field(name="Subflow Fwd Byts", dtype=Float64),
Field(name="Subflow Bwd Pkts", dtype=Float64),
Field(name="Subflow Bwd Byts", dtype=Float64),
Field(name="Init Fwd Win Byts", dtype=Float64),
Field(name="Init Bwd Win Byts", dtype=Float64),
Field(name="Fwd Act Data Pkts", dtype=Float64),
Field(name="Fwd Seg Size Min", dtype=Float64),
Field(name="Active Mean", dtype=Float64),
Field(name="Active Std", dtype=Float64),
Field(name="Active Max", dtype=Float64),
Field(name="Active Min", dtype=Float64),
        
        Field(name="Idle Mean", dtype=Float64),
        Field(name="Idle Std", dtype=Float64),
        Field(name="Idle Max", dtype=Float64),
        Field(name="Idle Min", dtype=Float64),
    ],
    source=source,
    online=True,
)